# =============================================================================
# alertmanager.yml - AlertManager configuration
# =============================================================================
global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@yourcompany.com'

templates:
  - '/etc/alertmanager/templates/*.tmpl'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

receivers:
  - name: 'web.hook'
    email_configs:
      - to: 'admin@yourcompany.com'
        subject: 'Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          {{ .Annotations.summary | default .Labels.alertname }}
          {{ .Annotations.description | default "n/a" }}
          {{ end }}

#    # Slack integration (optional)
#    slack_configs:
#      - api_url: '/etc/alertmanager/secrets/slack_webhook_url'
#        channel: '#alerts'
#        title: 'Alert: {{ .GroupLabels.alertname }}'
#        text: |
#          {{ range .Alerts }}
#          {{ .Annotations.summary }}
#          {{ .Annotations.description }}
#          {{ end }}
#
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
